FROM jenkins/jenkins:lts

USER root

# Install Docker CLI using static binary (robust and extremely fast)
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-27.1.1.tgz \
    && tar xzvf docker-27.1.1.tgz --strip-components=1 -C /usr/local/bin/ docker/docker \
    && rm docker-27.1.1.tgz

USER jenkins
